language: go
go:
- "1.20"

before_script:
- go install golang.org/x/tools/cmd/cover@latest
- go install github.com/mattn/goveralls@latest

script:
- go test -covermode=count -coverprofile=profile.cov ./...
- go vet ./...
- go test ./... -race
- goveralls -coverprofile=profile.cov -service=travis-ci
